parameters:
    database_driver: pdo_pgsql
    database_host: 10.0.2.2
    database_port: '9998'
    database_name: website
    database_user: website
    database_password: website
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 4f3ce6ba76d1a7e874e949a8a28107bab
    database_path: null
