parameters:
#    pion_iper.example.class: Pion\IperBundle\Example

services:
#    pion_iper.example:
#        class: %pion_iper.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
